version: "3.9"

services:
  server:
    build: ./server
    container_name: psi_server
    ports:
      - "9000:9000/udp"

  client:
    build: ./client
    container_name: psi_client
    depends_on:
      - server

networks:
  default:
    name: psi-net
