version: "3.9"

services:
  server:
    build: ./server
    container_name: psi_server
    # command: >
    #   sh -c "
    #   tc qdisc add dev eth0 root netem loss 20%;
    #   ./server
    #   " Uruchamia symulacje strat pakietow
    ports:
      - "9000:9000/udp"

  client:
    build: ./client
    container_name: psi_client
    depends_on:
      - server

networks:
  default:
    name: psi-net
